---
namespace: druid

stack:
  defines: process-group
  metadata:
    defines: metadata
    name: Apache Druid
    shortname: Apache Druid
    description: |
      Apache Druid (also known as Druid) is an open-source distributed data store designed to handle large-scale data sets and provide fast query performance for real-time and historical data. It is designed for use cases such as business intelligence, analytics, and event-driven applications.
      Druid uses a columnar storage format optimized for fast querying and aggregation of data. It supports both real-time and batch data ingestion and provides a scalable and fault-tolerant distributed architecture that can be easily scaled horizontally across multiple nodes.
      Druid includes a variety of built-in data ingestion tools that can handle a wide range of data sources, including log files, databases, and real-time streams. It also includes a SQL-like query language that allows users to query and aggregate data in real-time and historical contexts.
      Druid provides a variety of data processing features, including rollup, filtering, and grouping. It also includes support for machine learning algorithms and other advanced analytical functions. Druid includes a number of built-in visualization tools for creating charts, graphs, and other data visualizations.
    website: https://druid.apache.org/
    publisher: monk.io
    tags: real-time, real time, apache, kafka, open source, druid, streaming, database, analytics
    source: https://github.com/apache/druid
    icon: https://druid.apache.org/img/druid_nav.png
  runnable-list:
    - druid/dzookeeper
    - druid/db
    - druid/coordinator
    - druid/broker
    - druid/historical
    - druid/middlemanager
    - druid/router
